export {default as SignIn} from './SignIn.vue'
export {default as SignUp} from './SignUp.vue'
export {default as UserForm} from './User.vue'
export {default as ContactForm} from './Contact.vue'
export {default as UpdatePassword} from './UpdatePassword.vue'